# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 树上刺猬
content: 李朋的Blog
email: ljpww72729@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  一带一路.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ljpww72729.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ljpww72729
github_username:  ljpww72729


# Build settings
markdown: kramdown
#theme: minima
# plugins:
#   - jekyll-feed
#   - jekyll-sitemap
# #  - jekyll-seo-tag
#   - jemoji
#   - jekyll-paginate
#   - jekyll-github-metadata
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

  # 分页，每页包含博客的条数
paginate: 10
# 作者相关信息
author:
  name:       ljpww72729
  url:        http://ljpww72729.github.io

# Default YAML frontmatter settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
      author: "李朋"

# kramdown配置说明参见：https://kramdown.gettalong.org/options.html
kramdown:
  #设置toc显示的级别,不建议添加1号显示级别
  toc_levels: 4..6
  # GFM全称Github Flavored Markdown，是github出的markdown语法解析器
  # 参见：https://kramdown.gettalong.org/parser/gfm.html
  input: GFM
  auto_ids: true
  #entity_output: as_char
  #smart_quotes:  lsquo,rsquo,ldquo,rdquo
  #hard_wrap:    false
  #footnote_nr:  1
  #show_warnings: false
  # 参考：https://stackoverflow.com/questions/38417624/table-of-contents-using-jekyll-and-kramdown
  parse_block_html: true

  # 显示行号参见：https://github.com/jekyll/jekyll/issues/4619#issuecomment-191267346
  # 及https://kramdown.gettalong.org/syntax_highlighter/rouge.html
  syntax_highlighter: rouge
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

  # 博客链接格式，此处设置为none，采用/:categories/:title:output_ext该格式
  # 参见：https://jekyllrb.com/docs/permalinks/
permalink: none

category_dir: category/
tag_dir: tag/
search_dir: search/

# 摘要分隔符 参见：https://jekyllrb.com/docs/posts/#post-excerpts
excerpt_separator:  '<!-- more -->'

ga_ua: UA-96911884-1
disqus_name: ljpww72729

# Sass settings
sass:
    sass_dir: _sass
    style: :compressed

# 开启在内容更新后才build的功能，如果不更新则不build，这是实现性的功能
# 参见：https://jekyllrb.com/docs/configuration/#build-command-options
incremental: true
